### ISSUE TITLE
demo mode without hw dependency?

### ISSUE THREAD

**Issue by gavanderhoorn** [rosin-project/automatica18_scan_and_plan_demo#19]
Just wondering whether there is a launch file I could use to run this application without needing any actual hardware?

Similar to how Godel has the "full demo" mode.

**Comment by Chamango90** [comment]
Hi,
There is a launch file for a pure simulation:
```bash
Run application

# Simulation:
roslaunch snp_prbt_bringup application_bringup.launch
# Info: Make sure to press play in Gazebo
```
Is this what you mean? I don't know the Godel's full demo mode. 

Also if you want to automate the state-machine you could use additionally the script:
https://github.com/rosin-project/automatica18_scan_and_plan_demo/pull/17/files#diff-30522597c555988fee75f9ebded6223f

**Comment by gavanderhoorn** [comment]
thanks yes. That is what I meant.
